### ISSUE TITLE
Particle forker not opening in the proper directory

### ISSUE THREAD

**Issue by Pizzalol** [Myll/Dota-2-ModKit#32]
I have my Dota2Modkit and Steam in the D: directory but when I try to fork particles it only gives me the option to fork them to the C: directory

The forked particles will be messed up unless I make an exact folder structure in the C: directory due to the children particles having the C: directory path reference

**Comment by Myll** [comment]
If you put Modkit in your D drive and make a shortcut to it do you get the
same error?

On Feb 19, 2015, at 2:16 AM, Dario <notifications@github.com> wrote:

I have my Dota2Modkit and Steam in the D: directory but when I try to fork
particles it only gives me the option to fork them to the C: directory

The forked particles will be messed up unless I make an exact folder
structure in the C: directory due to the children particles having the C:
directory path reference

—
Reply to this email directly or view it on GitHub
<https://github.com/Myll/Dota-2-ModKit/issues/32>.

**Comment by Myll** [comment]
Nvm shouldnt matter since you already have Modkit in the D drive.

On Feb 19, 2015, at 2:16 AM, Dario <notifications@github.com> wrote:

I have my Dota2Modkit and Steam in the D: directory but when I try to fork
particles it only gives me the option to fork them to the C: directory

The forked particles will be messed up unless I make an exact folder
structure in the C: directory due to the children particles having the C:
directory path reference

—
Reply to this email directly or view it on GitHub
<https://github.com/Myll/Dota-2-ModKit/issues/32>.

**Comment by Myll** [comment]
Modkit is detecting your dota_ugc to be in the D drive. I'm confused by your setup. Do you have Dota installed in both drives? I will make an option to override the dota_ugc path.

**Comment by Pizzalol** [comment]
Steam/Dota is only in the D drive, Modkit is also in the D drive with a shortcut pinned on the taskbar

Everything seems to work fine apart from the fork directory, it always opens the C drive

**Comment by Myll** [comment]
Try going to preferences and manually changing the dota_ugc path in the latest vers, and then restarting modkit.

**Comment by Pizzalol** [comment]
Didnt fix it, still gives the option to open the C directory only

**Comment by Myll** [comment]
Try v1.4.7.7

**Comment by Pizzalol** [comment]
Fixed it, thanks!
